#!/bin/bash

# 이미 처리된 커밋이면 종료 (무한 루프 방지)
git log -1 --pretty=%B | grep -q "Commit Author:" && exit 0

HASH=$(git rev-parse --short HEAD)
AUTHOR_NAME=$(git config user.name)
AUTHOR_EMAIL=$(git config user.email)

MSG=$(git log -1 --pretty=%B)

# 이미 Commit 정보가 있으면 중복 방지
echo "$MSG" | grep -q "^---$" && exit 0

NEW_MSG="$MSG

---
Commit Author: $AUTHOR_NAME <$AUTHOR_EMAIL>"

git commit --amend -m "$NEW_MSG" --no-edit >/dev/null 2>&1
